openapi: 3.0.0
info:
  title: Job Portal API
  version: 1.0.0
paths:
  /api/transfer//get-transfer:
    get:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
  /api/transfer//request-transfer:
    post:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
  /api/transfer//transfer-response:
    post:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
  /api/auth//register:
    post:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
  /api/auth//login:
    post:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
  /api/auth//change-password:
    post:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
  /api/jobs//:
    post:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
  /api/jobs//on-demand-skills:
    get:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
  /api/jobs//on-demand-certifications:
    get:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
  /api/jobs//:jobId:
    put:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
  /api/jobs//:
    get:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
  /api/jobs//:jobId:
    get:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
  /api/jobs//jobs/:jobId/applicants/:employeeId/status:
    patch:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
  /api/jobs//jobs/:jobId/applicants/:employeeId/approve:
    patch:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
  /api/users//profile:
    get:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
  /api/users//profile/:employeeId:
    get:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
  /api/users//profile:
    put:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
  /api/users//profile/:employeeId:
    put:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
  /api/users//upload:
    post:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
  /api/users//applications:
    get:
      summary: TODO - Add summary
      responses:
        '200':
          description: Success
paths:
  /api/auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: securePassword123
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object

  /api/auth/register:
    post:
      summary: Register a new user (Admin only)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - role
              properties:
                name:
                  type: string
                email:
                  type: string
                role:
                  type: string
      responses:
        '201':
          description: User registered successfully

  /api/jobs/:
    post:
      summary: Create a job posting (Manager only)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - description
                - location
              properties:
                title:
                  type: string
                description:
                  type: string
                location:
                  type: string
      responses:
        '201':
          description: Job created successfully

  /api/transfer/request-transfer:
    post:
      summary: Request employee transfer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - fromManagerId
                - toManagerId
                - employeeId
                - jobId
              properties:
                fromManagerId:
                  type: string
                toManagerId:
                  type: string
                employeeId:
                  type: string
                jobId:
                  type: string
      responses:
        '200':
          description: Transfer request submitted

  /api/transfer/transfer-response:
    post:
      summary: Approve or reject a transfer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jobId
                - status
              properties:
                jobId:
                  type: string
                status:
                  type: string
                  enum: [approved, rejected]
      responses:
        '200':
          description: Transfer response recorded